
package ar.com.educacionit.ws.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InternalServerError", targetNamespace = "http://ws.educacionit.com.ar/")
public class InternalServerError
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ar.com.educacionit.ws.InternalServerError faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InternalServerError(String message, ar.com.educacionit.ws.InternalServerError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InternalServerError(String message, ar.com.educacionit.ws.InternalServerError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ar.com.educacionit.ws.InternalServerError
     */
    public ar.com.educacionit.ws.InternalServerError getFaultInfo() {
        return faultInfo;
    }

}
