
package ar.com.educacionit.ws.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ar.com.educacionit.ws.CreateProductoDTO;
import ar.com.educacionit.ws.ObjectFactory;
import ar.com.educacionit.ws.Producto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductoWSService", targetNamespace = "http://ws.educacionit.com.ar/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductoWSService {


    /**
     * 
     * @param codigo
     * @return
     *     returns ar.com.educacionit.ws.Producto
     * @throws InternalServerError
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductoByCodigo", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.GetProductoByCodigo")
    @ResponseWrapper(localName = "getProductoByCodigoResponse", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.GetProductoByCodigoResponse")
    @Action(input = "http://ws.educacionit.com.ar/ProductoWSService/getProductoByCodigoRequest", output = "http://ws.educacionit.com.ar/ProductoWSService/getProductoByCodigoResponse", fault = {
        @FaultAction(className = InternalServerError.class, value = "http://ws.educacionit.com.ar/ProductoWSService/getProductoByCodigo/Fault/InternalServerError")
    })
    public Producto getProductoByCodigo(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo)
        throws InternalServerError
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ar.com.educacionit.ws.Producto>
     * @throws InternalServerError
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllProductos", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.FindAllProductos")
    @ResponseWrapper(localName = "findAllProductosResponse", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.FindAllProductosResponse")
    @Action(input = "http://ws.educacionit.com.ar/ProductoWSService/findAllProductosRequest", output = "http://ws.educacionit.com.ar/ProductoWSService/findAllProductosResponse", fault = {
        @FaultAction(className = InternalServerError.class, value = "http://ws.educacionit.com.ar/ProductoWSService/findAllProductos/Fault/InternalServerError")
    })
    public List<Producto> findAllProductos()
        throws InternalServerError
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ar.com.educacionit.ws.Producto
     * @throws InternalServerError
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createProducto", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.CreateProducto")
    @ResponseWrapper(localName = "createProductoResponse", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.CreateProductoResponse")
    @Action(input = "http://ws.educacionit.com.ar/ProductoWSService/createProductoRequest", output = "http://ws.educacionit.com.ar/ProductoWSService/createProductoResponse", fault = {
        @FaultAction(className = InternalServerError.class, value = "http://ws.educacionit.com.ar/ProductoWSService/createProducto/Fault/InternalServerError")
    })
    public Producto createProducto(
        @WebParam(name = "arg0", targetNamespace = "")
        CreateProductoDTO arg0)
        throws InternalServerError
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ar.com.educacionit.ws.Producto
     * @throws InternalServerError
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProducto", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.UpdateProducto")
    @ResponseWrapper(localName = "updateProductoResponse", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.UpdateProductoResponse")
    @Action(input = "http://ws.educacionit.com.ar/ProductoWSService/updateProductoRequest", output = "http://ws.educacionit.com.ar/ProductoWSService/updateProductoResponse", fault = {
        @FaultAction(className = InternalServerError.class, value = "http://ws.educacionit.com.ar/ProductoWSService/updateProducto/Fault/InternalServerError")
    })
    public Producto updateProducto(
        @WebParam(name = "arg0", targetNamespace = "")
        CreateProductoDTO arg0)
        throws InternalServerError
    ;

    /**
     * 
     * @param codigo
     * @return
     *     returns ar.com.educacionit.ws.Producto
     * @throws InternalServerError
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteProducto", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.DeleteProducto")
    @ResponseWrapper(localName = "deleteProductoResponse", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.DeleteProductoResponse")
    @Action(input = "http://ws.educacionit.com.ar/ProductoWSService/deleteProductoRequest", output = "http://ws.educacionit.com.ar/ProductoWSService/deleteProductoResponse", fault = {
        @FaultAction(className = InternalServerError.class, value = "http://ws.educacionit.com.ar/ProductoWSService/deleteProducto/Fault/InternalServerError")
    })
    public Producto deleteProducto(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo)
        throws InternalServerError
    ;

}
