
package ar.com.educacionit.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductoWSServiceImplService", targetNamespace = "http://impl.ws.educacionit.com.ar/", wsdlLocation = "http://localhost:8082/?wsdl")
public class ProductoWSServiceImplService
    extends Service
{

    private final static URL PRODUCTOWSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTOWSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PRODUCTOWSSERVICEIMPLSERVICE_QNAME = new QName("http://impl.ws.educacionit.com.ar/", "ProductoWSServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTOWSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PRODUCTOWSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ProductoWSServiceImplService() {
        super(__getWsdlLocation(), PRODUCTOWSSERVICEIMPLSERVICE_QNAME);
    }

    public ProductoWSServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTOWSSERVICEIMPLSERVICE_QNAME, features);
    }

    public ProductoWSServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTOWSSERVICEIMPLSERVICE_QNAME);
    }

    public ProductoWSServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTOWSSERVICEIMPLSERVICE_QNAME, features);
    }

    public ProductoWSServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductoWSServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductoWSService
     */
    @WebEndpoint(name = "ProductoWSServiceImplPort")
    public ProductoWSService getProductoWSServiceImplPort() {
        return super.getPort(new QName("http://impl.ws.educacionit.com.ar/", "ProductoWSServiceImplPort"), ProductoWSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductoWSService
     */
    @WebEndpoint(name = "ProductoWSServiceImplPort")
    public ProductoWSService getProductoWSServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.educacionit.com.ar/", "ProductoWSServiceImplPort"), ProductoWSService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTOWSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PRODUCTOWSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PRODUCTOWSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
